### ISSUE TITLE
Fixed standing position

### ISSUE THREAD

**Issue by UnclePhonk** [der-fruhling-entertainment/create-train-perspective#14]
Most likely, this function does not depend on you, but still. How about fixing the player's camera in a standing position as well?.
When I didn't know about the existence of your mod, I tried to use "create: interactive", for the sake of fixing the camera inside the train (it works both standing and sitting), I didn't use any other functions, but the problem is that "interactive" is a big mod with a bunch of mechanics and problems I don't need (while he's in beta).

(I am incredibly grateful to you for this mod).

**Comment by der-fruhling** [comment]
Hi, thanks for posting this here!

This feature will be included in update [v0.2.2](https://github.com/der-fruhling-entertainment/create-train-perspective/milestone/1).

**Comment by UnclePhonk** [comment]
If you succeed, it will be very cool! Thanks
