### ISSUE TITLE
Support for versions like 1.19.2

### ISSUE THREAD

**Issue by KEVINIIE123** [der-fruhling-entertainment/create-train-perspective#48]
1.19.2 support would be nice, because a lot of other create additions haven't updated yet.
Maybe 1.18.2, but I feel like that is not as important.

**Comment by der-fruhling** [comment]
Implementing in #51 (future v0.4.0).

I think the project could do a 1.18.2 port as well, so I split that off into #49 as a separate tracking issue. It may or may not happen before v0.4.0.
