### ISSUE TITLE
The player turns on EVERY contrapion.

### ISSUE THREAD

**Issue by MrRedstoneToGo** [der-fruhling-entertainment/create-train-perspective#64]
**Is your feature request related to a problem? Please describe.**
When you're on the train, you turn with it, but not on a rollercoaster (minecart contraption). How would it be if this mod made it possible on all contraptions?

**Describe the solution you'd like**
How about turning on all contraptions?

**Comment by der-fruhling** [comment]
Honestly, I'm not a big fan of this idea. There are really only two cases where contraptions other than trains can turn (afaik):

With minecarts, the tracks are always at a 90° or 45° angle and the minecart immediately jumps to being that orientation. This would be incredibly jarring in practice. Slowly moving the camera to the minecarts position, which is a valid solution to this problem, is also jarring and not really what I'm going for with this mod (and have taken steps to avoid doing with trains).

With mechanical bearings, this could be implemented just fine. However, this is not super useful and creating Motion Sickness would already be covered by a turntable. I don't imagine that many people are riding on these things for much more than debugging, but I could see how they could be used for something like a merry-go-round style ride. This mod's functionality could be nice in this case.

Ultimately, I'm pretty happy with the way the mod works now, only applying the changes for trains. I'll think about it though.
