### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by GogUwU** [der-fruhling-entertainment/create-train-perspective#67]
**Describe the bug**
crash on start up

**To Reproduce**
1. install figura, immersive aircraft, create: train perspective
2. launch game

some more info: disabling any of those 3 mods will fix the issue

![all mods](https://github.com/der-fruhling-entertainment/create-train-perspective/assets/86622301/c454157a-f098-4d77-aaa9-d15bf99930c7)

[crash-2024-06-14_17.13.35-client.txt](https://github.com/user-attachments/files/15839256/crash-2024-06-14_17.13.35-client.txt)
[debug.log](https://github.com/user-attachments/files/15839257/debug.log)
[latest.log](https://github.com/user-attachments/files/15839258/latest.log)

**Comment by GogUwU** [comment]
forgot to say it's neoforge 1.20.1

**Comment by The-Weeb-Guy** [comment]
I got similar issues, tho i dont have immersive aircraft, it appears this issue happens with a wide variety of random mod combinations, so i stopped trying to narrow it down after adding _balm_ to the pack when i was trying to reconstruct the error and having it occur, but not when i added balm to a pack containing just train perspective and figura.

I was able to figure out on what version of create train perspective where the issue started, its anything beyond version 4.0
anyways heres my own, much worse crash report and log files
[debug.log](https://github.com/user-attachments/files/16419463/debug.log)
[latest.log](https://github.com/user-attachments/files/16419464/latest.log)
[crash-2024-07-29_17.50.01-client.txt](https://github.com/user-attachments/files/16419469/crash-2024-07-29_17.50.01-client.txt)

**Comment by der-fruhling** [comment]
Should be fixed in v0.6.0.

**Comment by GogUwU** [comment]
thx!
