### ISSUE TITLE
[1.18.2] Cloth config incorrect version requirement

### ISSUE THREAD

**Issue by V972** [der-fruhling-entertainment/create-train-perspective#70]
Latest cloth config version is 6.5.xxx on both [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/cloth-config/files/all?filter-game-version=2020709689%3A9008) and [Modrinth](https://modrinth.com/mod/cloth-config/versions?g=1.18.2).
Yet the new 1.0.0 version requries >= 8.

Minecraft 1.18.2
Forge 40.2.21
[Create: Train Perspective v1.0.0](https://modrinth.com/mod/create-train-perspective/version/1.0.0+forge-1.18.2)

**Comment by der-fruhling** [comment]
Fixed in v1.0.1 (for 1.18.2 only).

Thanks!
