### ISSUE TITLE
Camera moving an angle greater than necessary

### ISSUE THREAD

**Issue by Pikamochzo** [der-fruhling-entertainment/create-train-perspective#71]
Camera is turning more than necessary

**To Reproduce**
1. Mount any create contraption

**Expected behavior**
More or less 1 to 1 camera movement

**Screenshots**
https://drive.google.com/file/d/1Q6tNDs4reqt3Am2KChtQLkw1Zx_UITFe/view?usp=sharing

**Comment by der-fruhling** [comment]
This issue is caused by the option **"Rotate when seated"** being added into Create, which implements that functionality of this mod. You can fix this by disabling this option in Create's client config.

**Comment by der-fruhling** [comment]
This will be worked around automagically in version 1.1.0.
