### ISSUE TITLE
Rolled camera results in diagonal movement of mouse

### ISSUE THREAD

**Issue by FlashOfAsh** [der-fruhling-entertainment/create-train-perspective#72]
**Describe the bug**
When camera is rolled (not pitched), looking up and down acts like you're looking diagonally

**To Reproduce**
Create a train
get it on some sort of ramp, steeper makes it more obvious
look perpendicular to track for maximum effect
input only up and down mouse movement

**Expected behavior**
looking what the game ironically does think of as diagonal mouse movement

**Screenshots**
Note, despite this containing steam and rails specific train stuff, this DOES apply to normal trains
![image](https://github.com/user-attachments/assets/886f7e05-d4b2-4d27-a7c0-f826f2895140)
here is a more direct illustration of the problem
![image](https://github.com/user-attachments/assets/9778d1f8-5b43-46d8-827b-5c450098b48e)

**Comment by der-fruhling** [comment]
Should be fixed in v1.1.0
