### ISSUE TITLE
Cloth config required or game crashes

### ISSUE THREAD

**Issue by Aces-and-Jacks** [der-fruhling-entertainment/create-train-perspective#75]
**Describe the bug**
The game crashes without cloth config, However modrinth says optional.

**To Reproduce**
1. Start game without cloth config
2. crash

**Expected behavior**
If the mod was optional wouldn't crash.

**Screenshots**

**Logs**
https://mclo.gs/LYL3NaF

**Sugestion**
make cloth config required

**Extras**
I'm pretty sure this is the mod causeing the crash when reading the crash report. Looked on modrinth which said optional. However if it causes the crash it'd be required. I'm on 1.20.1 fabric. Sorry if this sounded rude, or if I got the wrong mod

**Comment by der-fruhling** [comment]
Will be fixed in v1.1.0. Thanks for reporting this!
